In [1]:
import torch

In [2]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])
y_train = torch.tensor([0, 0, 0, 1, 1])
 
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])
y_test = torch.tensor([0, 1])

In [3]:
y_train

tensor([0, 0, 0, 1, 1])

In [8]:
print(X_train[4:,0])

tensor([2.7000])


In [11]:
X_train.shape[0]

5

In [3]:
import time
import asyncio

async def say_after(delay, what):
    await asyncio.sleep(delay)
    print(what)

async def main():
    print(f"started at {time.strftime('%X')}")

    await say_after(1, 'hello')
    await say_after(2, 'world')

    print(f"finished at {time.strftime('%X')}")

# asyncio.run(main())
await main()

started at 21:57:53
hello
world
finished at 21:57:56


In [13]:
import tiktoken
import torch

In [14]:
tokenizer = tiktoken.get_encoding("gpt2")

In [15]:
text = "Your journey starts with one step"

In [16]:
integers = tokenizer.encode(text)

In [17]:
integers = torch.tensor(integers)

In [18]:
integers

tensor([7120, 7002, 4940,  351,  530, 2239])

In [31]:
torch.manual_seed(123)
vocab_size = 50257
output_dim = 3
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [32]:
probs = torch.softmax(embedding_layer.weight, dim=1)

In [33]:
print(embedding_layer(integers))

tensor([[ 0.6727,  0.2474, -1.6642],
        [ 1.0490,  0.3580, -0.6994],
        [ 2.5301,  0.3388, -0.2527],
        [ 0.3171, -0.8529, -1.4709],
        [-1.4560,  1.1582,  0.2196],
        [-1.4948,  0.2331, -1.2366]], grad_fn=<EmbeddingBackward0>)


In [45]:
def softmax_naive(x):
    expFn = torch.exp(x) / torch.exp(x).sum(dim=0)
    return expFn / expFn.sum(dim=0)

In [46]:
embedding_layer_normalized = softmax_naive(embedding_layer(integers))

In [42]:
embedding_layer_normalized

tensor([[0.1021, 0.1425, 0.0586],
        [0.1487, 0.1592, 0.1539],
        [0.6539, 0.1561, 0.2406],
        [0.0715, 0.0474, 0.0712],
        [0.0121, 0.3543, 0.3858],
        [0.0117, 0.1405, 0.0899]], grad_fn=<DivBackward0>)

In [16]:
import torch
input = torch.tensor([1, 0, 0])
mask = torch.tensor([[1, 0, 0], [0, 1, 1]])
masked = torch.nonzero(mask)
print(masked)
indices = masked.squeeze(-1)
print(indices)

tensor([[0, 0],
        [1, 1],
        [1, 2]])
tensor([[0, 0],
        [1, 1],
        [1, 2]])
